Option Explicit On
'
' Copyright (c) 2014 Crewstone Consulting ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
'
Imports System
Imports System.Configuration
Imports System.Data
Imports System.Xml.Serialization
Imports DotNetNuke
Imports DotNetNuke.Common.Utilities

Namespace Namespace.Modules.Race2012

    ''' <summary>
    ''' The Info class for ContactTypes
    ''' </summary>
    ''' <remarks>
    ''' </remarks>
    ''' <history>
	''' Generated by CodeSmith on Friday, January 17, 2014
    ''' </history>
    ''' -----------------------------------------------------------------------------
    <Serializable(), XmlRoot("ContactTypes")> _
	Public Class ContactTypesInfo
		Implements Entities.Modules.IHydratable

#Region "Private Members"
		Private _contactType as Integer
		Private _portalId as Integer
		Private _abbreviation as String = string.Empty
		Private _description as String = string.Empty
		Private _defaultType as Boolean
#End Region

#Region "Constructors"
        ' initialization
        Public Sub New()
        End Sub
		
        Public Sub New(ByVal contactType As Integer, ByVal portalId As Integer, ByVal abbreviation As String, ByVal description As String, ByVal defaultType As Boolean)
            Me.PortalId = PortalId
            Me.ContactType = ContactType
            Me.Abbreviation = Abbreviation
            Me.Description = Description
            Me.DefaultType = DefaultType
        End Sub
#End Region

#Region "Public Properties"
		' <summary>
		' Gets and sets the ContactType
		' </summary>
        <XmlIgnore()> _
		Public Property ContactType() as Integer
			Get
				Return _contactType
			End Get
			Set(ByVal Value as Integer)
				_contactType = Value
			End Set
		End Property
		
		' <summary>
		' Gets and sets the PortalId
		' </summary>
        <XmlIgnore()> _
        <XmlAttribute("PortalId")> _
		Public Property PortalId() as Integer 
			Get
				Return _portalId
			End Get
			Set(ByVal Value as Integer)
				_portalId = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of PortalId
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property PortalIdText() as String
			Get
				Return _portalId.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the Abbreviation
		' </summary>
        <XmlAttribute("Abbreviation")> _
		Public Property Abbreviation() as String 
			Get
				Return _abbreviation
			End Get
			Set(ByVal Value as String)
				_abbreviation = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the Description
		' </summary>
        <XmlAttribute("Description")> _
		Public Property Description() as String 
			Get
				Return _description
			End Get
			Set(ByVal Value as String)
				_description = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the DefaultType
		' </summary>
        <XmlAttribute("DefaultType")> _
		Public Property DefaultType() as Boolean 
			Get
				Return _defaultType
			End Get
			Set(ByVal Value as Boolean)
				_defaultType = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of DefaultType
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property DefaultTypeText() as String
			Get
				Return _defaultType.ToString()
			End Get
		End Property
#End Region

#Region "IHydratable Implementation"
       <XmlIgnore()> _
       Public Property KeyID() As Integer Implements Entities.Modules.IHydratable.KeyID
            Get
		       Return ContactType 
            End Get
            Set(ByVal value As Integer)
		       ContactType = value
		       End Set
        End Property
 
        Public Sub Fill(ByVal dr As IDataReader) Implements Entities.Modules.IHydratable.Fill
  
		       ContactType = Convert.ToInt32(Null.SetNull(dr.Item("ContactType"), ContactType))
		       PortalId = Convert.ToInt32(Null.SetNull(dr.Item("PortalId"), PortalId))
		       Abbreviation = Convert.ToString(Null.SetNull(dr.Item("Abbreviation"), Abbreviation))
		       Description = Convert.ToString(Null.SetNull(dr.Item("Description"), Description))
		       DefaultType = Convert.ToBoolean(Null.SetNull(dr.Item("DefaultType"), DefaultType))
		End Sub
#End Region
    End Class

End Namespace
