Option Explicit On
'
' Copyright (c) 2014 Crewstone Consulting ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
'
Imports System
Imports System.Configuration
Imports System.Data
Imports System.Xml.Serialization
Imports DotNetNuke
Imports DotNetNuke.Common.Utilities

Namespace Namespace.Modules.Race2012

    ''' <summary>
    ''' The Info class for DoNotEmail
    ''' </summary>
    ''' <remarks>
    ''' </remarks>
    ''' <history>
	''' Generated by CodeSmith on Friday, January 17, 2014
    ''' </history>
    ''' -----------------------------------------------------------------------------
    <Serializable(), XmlRoot("DoNotEmail")> _
	Public Class DoNotEmailInfo
		Implements Entities.Modules.IHydratable

#Region "Private Members"
		Private _emailAddress as String = string.Empty
		Private _portalId as Integer
		Private _movedBy as String = string.Empty
		Private _optOutReason as String = string.Empty
#End Region

#Region "Constructors"
        ' initialization
        Public Sub New()
        End Sub
		
        Public Sub New(ByVal emailAddress As String, ByVal portalId As Integer, ByVal movedBy As String, ByVal optOutReason As String)
            Me.PortalId = PortalId
            Me.EmailAddress = EmailAddress
            Me.MovedBy = MovedBy
            Me.OptOutReason = OptOutReason
        End Sub
#End Region

#Region "Public Properties"
		' <summary>
		' Gets and sets the EmailAddress
		' </summary>
        <XmlIgnore()> _
		Public Property EmailAddress() as String
			Get
				Return _emailAddress
			End Get
			Set(ByVal Value as String)
				_emailAddress = Value
			End Set
		End Property
		
		' <summary>
		' Gets and sets the PortalId
		' </summary>
        <XmlIgnore()> _
        <XmlAttribute("PortalId")> _
		Public Property PortalId() as Integer 
			Get
				Return _portalId
			End Get
			Set(ByVal Value as Integer)
				_portalId = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of PortalId
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property PortalIdText() as String
			Get
				Return _portalId.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the MovedBy
		' </summary>
        <XmlAttribute("MovedBy")> _
		Public Property MovedBy() as String 
			Get
				Return _movedBy
			End Get
			Set(ByVal Value as String)
				_movedBy = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the OptOutReason
		' </summary>
        <XmlAttribute("OptOutReason")> _
		Public Property OptOutReason() as String 
			Get
				Return _optOutReason
			End Get
			Set(ByVal Value as String)
				_optOutReason = Value
			End Set
		End Property
#End Region

#Region "IHydratable Implementation"
       <XmlIgnore()> _
       Public Property KeyID() As Integer Implements Entities.Modules.IHydratable.KeyID
            Get
		       Return EmailAddress 
            End Get
            Set(ByVal value As Integer)
		       EmailAddress = value
		       End Set
        End Property
 
        Public Sub Fill(ByVal dr As IDataReader) Implements Entities.Modules.IHydratable.Fill
  
		       EmailAddress = Convert.ToString(Null.SetNull(dr.Item("EmailAddress"), EmailAddress))
		       PortalId = Convert.ToInt32(Null.SetNull(dr.Item("PortalId"), PortalId))
		       MovedBy = Convert.ToString(Null.SetNull(dr.Item("MovedBy"), MovedBy))
		       OptOutReason = Convert.ToString(Null.SetNull(dr.Item("OptOutReason"), OptOutReason))
		End Sub
#End Region
    End Class

End Namespace
