Option Explicit On
'
' Copyright (c) 2014 Crewstone Consulting ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
'
Imports System
Imports System.Configuration
Imports System.Data
Imports System.Xml.Serialization
Imports DotNetNuke
Imports DotNetNuke.Common.Utilities

Namespace Namespace.Modules.Race2012

    ''' <summary>
    ''' The Info class for EventTypes
    ''' </summary>
    ''' <remarks>
    ''' </remarks>
    ''' <history>
	''' Generated by CodeSmith on Friday, January 17, 2014
    ''' </history>
    ''' -----------------------------------------------------------------------------
    <Serializable(), XmlRoot("EventTypes")> _
	Public Class EventTypesInfo
		Implements Entities.Modules.IHydratable

#Region "Private Members"
		Private _eventTypeId as Integer
		Private _portalId as Integer
		Private _eventTypeName as String = string.Empty
		Private _defaultType as short
#End Region

#Region "Constructors"
        ' initialization
        Public Sub New()
        End Sub
		
        Public Sub New(ByVal eventTypeId As Integer, ByVal portalId As Integer, ByVal eventTypeName As String, ByVal defaultType As short)
            Me.PortalId = PortalId
            Me.EventTypeId = EventTypeId
            Me.EventTypeName = EventTypeName
            Me.DefaultType = DefaultType
        End Sub
#End Region

#Region "Public Properties"
		' <summary>
		' Gets and sets the EventTypeId
		' </summary>
        <XmlIgnore()> _
		Public Property EventTypeId() as Integer
			Get
				Return _eventTypeId
			End Get
			Set(ByVal Value as Integer)
				_eventTypeId = Value
			End Set
		End Property
		
		' <summary>
		' Gets and sets the PortalId
		' </summary>
        <XmlIgnore()> _
        <XmlAttribute("PortalId")> _
		Public Property PortalId() as Integer 
			Get
				Return _portalId
			End Get
			Set(ByVal Value as Integer)
				_portalId = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of PortalId
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property PortalIdText() as String
			Get
				Return _portalId.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the EventTypeName
		' </summary>
        <XmlAttribute("EventTypeName")> _
		Public Property EventTypeName() as String 
			Get
				Return _eventTypeName
			End Get
			Set(ByVal Value as String)
				_eventTypeName = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the DefaultType
		' </summary>
        <XmlAttribute("DefaultType")> _
		Public Property DefaultType() as short 
			Get
				Return _defaultType
			End Get
			Set(ByVal Value as short)
				_defaultType = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of DefaultType
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property DefaultTypeText() as String
			Get
				Return _defaultType.ToString()
			End Get
		End Property
#End Region

#Region "IHydratable Implementation"
       <XmlIgnore()> _
       Public Property KeyID() As Integer Implements Entities.Modules.IHydratable.KeyID
            Get
		       Return EventTypeId 
            End Get
            Set(ByVal value As Integer)
		       EventTypeId = value
		       End Set
        End Property
 
        Public Sub Fill(ByVal dr As IDataReader) Implements Entities.Modules.IHydratable.Fill
  
		       EventTypeId = Convert.ToInt32(Null.SetNull(dr.Item("EventTypeId"), EventTypeId))
		       PortalId = Convert.ToInt32(Null.SetNull(dr.Item("PortalId"), PortalId))
		       EventTypeName = Convert.ToString(Null.SetNull(dr.Item("EventTypeName"), EventTypeName))
		       DefaultType = Convert.ToInt16(Null.SetNull(dr.Item("DefaultType"), DefaultType))
		End Sub
#End Region
    End Class

End Namespace
