Option Explicit On
'
' Copyright (c) 2014 Crewstone Consulting ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
'
Imports System
Imports System.Configuration
Imports System.Data
Imports System.Xml.Serialization
Imports DotNetNuke
Imports DotNetNuke.Common.Utilities

Namespace Namespace.Modules.Race2012

    ''' <summary>
    ''' The Info class for MemberTypes
    ''' </summary>
    ''' <remarks>
    ''' </remarks>
    ''' <history>
	''' Generated by CodeSmith on Friday, January 17, 2014
    ''' </history>
    ''' -----------------------------------------------------------------------------
    <Serializable(), XmlRoot("MemberTypes")> _
	Public Class MemberTypesInfo
		Implements Entities.Modules.IHydratable

#Region "Private Members"
		Private _memberTypeID as Integer
		Private _portalId as Integer
		Private _memberType as String = string.Empty
		Private _memberDues as decimal
#End Region

#Region "Constructors"
        ' initialization
        Public Sub New()
        End Sub
		
        Public Sub New(ByVal memberTypeID As Integer, ByVal portalId As Integer, ByVal memberType As String, ByVal memberDues As decimal)
            Me.PortalId = PortalId
            Me.MemberTypeID = MemberTypeID
            Me.MemberType = MemberType
            Me.MemberDues = MemberDues
        End Sub
#End Region

#Region "Public Properties"
		' <summary>
		' Gets and sets the MemberTypeID
		' </summary>
        <XmlIgnore()> _
		Public Property MemberTypeID() as Integer
			Get
				Return _memberTypeID
			End Get
			Set(ByVal Value as Integer)
				_memberTypeID = Value
			End Set
		End Property
		
		' <summary>
		' Gets and sets the PortalId
		' </summary>
        <XmlIgnore()> _
        <XmlAttribute("PortalId")> _
		Public Property PortalId() as Integer 
			Get
				Return _portalId
			End Get
			Set(ByVal Value as Integer)
				_portalId = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of PortalId
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property PortalIdText() as String
			Get
				Return _portalId.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the MemberType
		' </summary>
        <XmlAttribute("MemberType")> _
		Public Property MemberType() as String 
			Get
				Return _memberType
			End Get
			Set(ByVal Value as String)
				_memberType = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the MemberDues
		' </summary>
        <XmlAttribute("MemberDues")> _
		Public Property MemberDues() as decimal 
			Get
				Return _memberDues
			End Get
			Set(ByVal Value as decimal)
				_memberDues = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of MemberDues
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property MemberDuesText() as String
			Get
				Return _memberDues.ToString()
			End Get
		End Property
#End Region

#Region "IHydratable Implementation"
       <XmlIgnore()> _
       Public Property KeyID() As Integer Implements Entities.Modules.IHydratable.KeyID
            Get
		       Return MemberTypeID 
            End Get
            Set(ByVal value As Integer)
		       MemberTypeID = value
		       End Set
        End Property
 
        Public Sub Fill(ByVal dr As IDataReader) Implements Entities.Modules.IHydratable.Fill
  
		       MemberTypeID = Convert.ToInt32(Null.SetNull(dr.Item("MemberTypeID"), MemberTypeID))
		       PortalId = Convert.ToInt32(Null.SetNull(dr.Item("PortalId"), PortalId))
		       MemberType = Convert.ToString(Null.SetNull(dr.Item("MemberType"), MemberType))
		       MemberDues = Convert.ToDecimal(Null.SetNull(dr.Item("MemberDues"), MemberDues))
		End Sub
#End Region
    End Class

End Namespace
