Option Explicit On
'
' Copyright (c) 2014 Crewstone Consulting ltd
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
'
Imports System
Imports System.Configuration
Imports System.Data
Imports System.Xml.Serialization
Imports DotNetNuke
Imports DotNetNuke.Common.Utilities

Namespace Namespace.Modules.Race2012

    ''' <summary>
    ''' The Info class for RaceDivisions
    ''' </summary>
    ''' <remarks>
    ''' </remarks>
    ''' <history>
	''' Generated by CodeSmith on Friday, January 17, 2014
    ''' </history>
    ''' -----------------------------------------------------------------------------
    <Serializable(), XmlRoot("RaceDivisions")> _
	Public Class RaceDivisionsInfo

#Region "Private Members"
		Private _raceId as Integer
		Private _priority as Integer
		Private _portalId as Integer
		Private _sex as String = string.Empty
		Private _startAge as short
		Private _endAge as Integer
		Private _startWeight as Integer
		Private _endWeight as Integer
		Private _survivor as Boolean
		Private _division as String = string.Empty
		Private _depth as short
		Private _overall as Boolean
		Private _masters as Boolean
		Private _uSATF as Boolean
#End Region

#Region "Constructors"
        ' initialization
        Public Sub New()
        End Sub
		
        Public Sub New(ByVal raceId As Integer, ByVal priority As Integer, ByVal portalId As Integer, ByVal sex As String, ByVal startAge As short, ByVal endAge As Integer, ByVal startWeight As Integer, ByVal endWeight As Integer, ByVal survivor As Boolean, ByVal division As String, ByVal depth As short, ByVal overall As Boolean, ByVal masters As Boolean, ByVal uSATF As Boolean)
            Me.PortalId = PortalId
            Me.RaceId = RaceId
            Me.Priority = Priority
            Me.Sex = Sex
            Me.StartAge = StartAge
            Me.EndAge = EndAge
            Me.StartWeight = StartWeight
            Me.EndWeight = EndWeight
            Me.Survivor = Survivor
            Me.Division = Division
            Me.Depth = Depth
            Me.Overall = Overall
            Me.Masters = Masters
            Me.USATF = USATF
        End Sub
#End Region

#Region "Public Properties"
		' <summary>
		' Gets and sets the RaceId
		' Race Identifier
		' </summary>
        <XmlIgnore()> _
		Public Property RaceId() as Integer
			Get
				Return _raceId
			End Get
			Set(ByVal Value as Integer)
				_raceId = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the Priority
		' Award Division Priority
		' </summary>
        <XmlIgnore()> _
		Public Property Priority() as Integer
			Get
				Return _priority
			End Get
			Set(ByVal Value as Integer)
				_priority = Value
			End Set
		End Property
		
		' <summary>
		' Gets and sets the PortalId
		' </summary>
        <XmlIgnore()> _
        <XmlAttribute("PortalId")> _
		Public Property PortalId() as Integer 
			Get
				Return _portalId
			End Get
			Set(ByVal Value as Integer)
				_portalId = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of PortalId
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property PortalIdText() as String
			Get
				Return _portalId.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the Sex
		' Gender
		' </summary>
        <XmlAttribute("Sex")> _
		Public Property Sex() as String 
			Get
				Return _sex
			End Get
			Set(ByVal Value as String)
				_sex = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the StartAge
		' Start of Age Group
		' </summary>
        <XmlAttribute("StartAge")> _
		Public Property StartAge() as short 
			Get
				Return _startAge
			End Get
			Set(ByVal Value as short)
				_startAge = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of StartAge
		' Start of Age Group
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property StartAgeText() as String
			Get
				Return _startAge.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the EndAge
		' End of Age Group
		' </summary>
        <XmlAttribute("EndAge")> _
		Public Property EndAge() as Integer 
			Get
				Return _endAge
			End Get
			Set(ByVal Value as Integer)
				_endAge = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of EndAge
		' End of Age Group
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property EndAgeText() as String
			Get
				Return _endAge.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the StartWeight
		' Start of Weight Group
		' </summary>
        <XmlAttribute("StartWeight")> _
		Public Property StartWeight() as Integer 
			Get
				Return _startWeight
			End Get
			Set(ByVal Value as Integer)
				_startWeight = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of StartWeight
		' Start of Weight Group
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property StartWeightText() as String
			Get
				Return _startWeight.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the EndWeight
		' End of Weight Group
		' </summary>
        <XmlAttribute("EndWeight")> _
		Public Property EndWeight() as Integer 
			Get
				Return _endWeight
			End Get
			Set(ByVal Value as Integer)
				_endWeight = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of EndWeight
		' End of Weight Group
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property EndWeightText() as String
			Get
				Return _endWeight.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the Survivor
		' Cancer Survivor
		' </summary>
        <XmlAttribute("Survivor")> _
		Public Property Survivor() as Boolean 
			Get
				Return _survivor
			End Get
			Set(ByVal Value as Boolean)
				_survivor = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of Survivor
		' Cancer Survivor
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property SurvivorText() as String
			Get
				Return _survivor.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the Division
		' Division
		' </summary>
        <XmlAttribute("Division")> _
		Public Property Division() as String 
			Get
				Return _division
			End Get
			Set(ByVal Value as String)
				_division = Value
			End Set
		End Property

		' <summary>
		' Gets and sets the Depth
		' Award Depth
		' </summary>
        <XmlAttribute("Depth")> _
		Public Property Depth() as short 
			Get
				Return _depth
			End Get
			Set(ByVal Value as short)
				_depth = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of Depth
		' Award Depth
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property DepthText() as String
			Get
				Return _depth.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the Overall
		' Open or Overall Category
		' </summary>
        <XmlAttribute("Overall")> _
		Public Property Overall() as Boolean 
			Get
				Return _overall
			End Get
			Set(ByVal Value as Boolean)
				_overall = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of Overall
		' Open or Overall Category
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property OverallText() as String
			Get
				Return _overall.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the Masters
		' Masters Category
		' </summary>
        <XmlAttribute("Masters")> _
		Public Property Masters() as Boolean 
			Get
				Return _masters
			End Get
			Set(ByVal Value as Boolean)
				_masters = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of Masters
		' Masters Category
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property MastersText() as String
			Get
				Return _masters.ToString()
			End Get
		End Property

		' <summary>
		' Gets and sets the USATF
		' USATF Division
		' </summary>
        <XmlAttribute("USATF")> _
		Public Property USATF() as Boolean 
			Get
				Return _uSATF
			End Get
			Set(ByVal Value as Boolean)
				_uSATF = Value
			End Set
		End Property
		' <summary>
		' Read-only formatted text version of USATF
		' USATF Division
		' </summary>
        <XmlIgnore()> _
		Public Readonly Property USATFText() as String
			Get
				Return _uSATF.ToString()
			End Get
		End Property
#End Region

#Region "IHydratable Implementation"
#End Region
    End Class

End Namespace
