Option Explicit On

Imports System
Imports System.Configuration
Imports System.Data
Imports System.Xml.Serialization
Imports DotNetNuke

Namespace Crewstone Consulting ltd.Modules.Race2012

    ''' <summary>
    ''' The base class for Race2012
    ''' </summary>
    ''' <remarks>
    ''' This class contains all the collections used for import and export processing
    ''' </remarks>
    ''' <history>
	''' Generated by CodeSmith on Friday, January 17, 2014
    ''' </history>
    ''' -----------------------------------------------------------------------------
    <Serializable(), XmlRoot("Race2012")> _
	Public Class Race2012


#Region "Private Members"
        Private _Bouncess As Generic.List(Of BouncesInfo)
        Private _ContactTypess As Generic.List(Of ContactTypesInfo)
        Private _Divisionss As Generic.List(Of DivisionsInfo)
        Private _DoNotEmails As Generic.List(Of DoNotEmailInfo)
        Private _Entrantss As Generic.List(Of EntrantsInfo)
        Private _Eventss As Generic.List(Of EventsInfo)
        Private _EventTypess As Generic.List(Of EventTypesInfo)
        Private _MemberTypess As Generic.List(Of MemberTypesInfo)
        Private _Organizations As Generic.List(Of OrganizationInfo)
        Private _RaceDivisionss As Generic.List(Of RaceDivisionsInfo)
        Private _Racess As Generic.List(Of RacesInfo)
        Private _ZIPs As Generic.List(Of ZIPInfo)
#End Region

#Region "Constructors"
        ' initialization
        Public Sub New()
        End Sub
		
#End Region

#Region "Public Properties"
		' <summary>
		' Gets and sets the Bounces
		' Bad Email Addresses
		' </summary>
        <XmlElement("Bouncess")> _
		Public Property Bouncess() As Generic.List(Of BouncesInfo)
			Get
				Return _Bouncess
			End Get
			Set(ByVal Value As Generic.List(Of BouncesInfo))
				 _Bouncess = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the ContactTypes
		' </summary>
        <XmlElement("ContactTypess")> _
		Public Property ContactTypess() As Generic.List(Of ContactTypesInfo)
			Get
				Return _ContactTypess
			End Get
			Set(ByVal Value As Generic.List(Of ContactTypesInfo))
				 _ContactTypess = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the Divisions
		' </summary>
        <XmlElement("Divisionss")> _
		Public Property Divisionss() As Generic.List(Of DivisionsInfo)
			Get
				Return _Divisionss
			End Get
			Set(ByVal Value As Generic.List(Of DivisionsInfo))
				 _Divisionss = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the DoNotEmail
		' </summary>
        <XmlElement("DoNotEmails")> _
		Public Property DoNotEmails() As Generic.List(Of DoNotEmailInfo)
			Get
				Return _DoNotEmails
			End Get
			Set(ByVal Value As Generic.List(Of DoNotEmailInfo))
				 _DoNotEmails = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the Entrants
		' Club member and event participant demographic information
		' </summary>
        <XmlElement("Entrantss")> _
		Public Property Entrantss() As Generic.List(Of EntrantsInfo)
			Get
				Return _Entrantss
			End Get
			Set(ByVal Value As Generic.List(Of EntrantsInfo))
				 _Entrantss = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the Events
		' </summary>
        <XmlElement("Eventss")> _
		Public Property Eventss() As Generic.List(Of EventsInfo)
			Get
				Return _Eventss
			End Get
			Set(ByVal Value As Generic.List(Of EventsInfo))
				 _Eventss = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the EventTypes
		' </summary>
        <XmlElement("EventTypess")> _
		Public Property EventTypess() As Generic.List(Of EventTypesInfo)
			Get
				Return _EventTypess
			End Get
			Set(ByVal Value As Generic.List(Of EventTypesInfo))
				 _EventTypess = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the MemberTypes
		' </summary>
        <XmlElement("MemberTypess")> _
		Public Property MemberTypess() As Generic.List(Of MemberTypesInfo)
			Get
				Return _MemberTypess
			End Get
			Set(ByVal Value As Generic.List(Of MemberTypesInfo))
				 _MemberTypess = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the Organization
		' </summary>
        <XmlElement("Organizations")> _
		Public Property Organizations() As Generic.List(Of OrganizationInfo)
			Get
				Return _Organizations
			End Get
			Set(ByVal Value As Generic.List(Of OrganizationInfo))
				 _Organizations = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the RaceDivisions
		' </summary>
        <XmlElement("RaceDivisionss")> _
		Public Property RaceDivisionss() As Generic.List(Of RaceDivisionsInfo)
			Get
				Return _RaceDivisionss
			End Get
			Set(ByVal Value As Generic.List(Of RaceDivisionsInfo))
				 _RaceDivisionss = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the Races
		' Descriptive information for all races
		' </summary>
        <XmlElement("Racess")> _
		Public Property Racess() As Generic.List(Of RacesInfo)
			Get
				Return _Racess
			End Get
			Set(ByVal Value As Generic.List(Of RacesInfo))
				 _Racess = Value
			End Set
		End Property	
		' <summary>
		' Gets and sets the ZIP
		' </summary>
        <XmlElement("ZIPs")> _
		Public Property ZIPs() As Generic.List(Of ZIPInfo)
			Get
				Return _ZIPs
			End Get
			Set(ByVal Value As Generic.List(Of ZIPInfo))
				 _ZIPs = Value
			End Set
		End Property	
#End Region


    End Class

End Namespace

